version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExternalGitProjectJakarthaTestProject
  gitServerName: GH_SK_Shared
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
- name: Package2
  version: "1.0"
  gitServerName: GH_SK_Shared
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.externalgitprojectjakarthatest.integrations:Test2
  packages:
  - name: ExternalGitProjectJakarthaTestProject
    version: "1.0"
  - name: Package2
    version: "1.0"
- serviceName: Package2:flowservice2
  packages:
  - name: Package2
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.1114
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 12.1.0.0.1114
- serviceName: project.externalgitprojectjakarthatest.integrations:TestFlow1
  packages:
  - name: ExternalGitProjectJakarthaTestProject
    version: "1.0"
  - name: Package2
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 12.1.0.0.1114
